name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Step 3: Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        region: ap-south-1
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Step 4: Login to Amazon ECR and setup ECR private repository
    - name: Login and Setup ECR Private Repository
      uses: deploy-actions/setup-ecr@v1.0.0
      with:
        RepositoryName: newrepo       # ECR repository name
        ImageTagMutability: MUTABLE   # Image tag mutability
        AwsRegion: ap-south-1         # AWS region

    # Step 5: Push Docker image to Amazon ECR
    - name: AWS ECR Push
      uses: xcpep/aws-ecr-push-action@v0.1
      with:
        repo: newrepo                # Replace with your ECR repository name
        region: ap-south-1
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        create_repo: true            # Set to true if you want to create the repository if it doesn't exist
        tags: latest                 # Tag for your Docker image
        dockerfile: Dockerfile       # Path to your Dockerfile
        path: .                      # Path to the build context
