name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-south-1
        aws-access-key-id: AKIAWMFUO7WNPCDIJVV4
        aws-secret-access-key: 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
    - name: Login Amazon ECR and Setup ECR Private Repository
      uses: deploy-actions/setup-ecr@v1.0.0
      with:
       # The name to use for the private repository.
        RepositoryName: newrepo
       # The tag mutability setting for the repository. This input is always applied.
        ImageTagMutability: MUTABLE
       # AWS Region, e.g. us-east-2
        AwsRegion: ap-south-1
    - name: AWS ECR Push
  # You may pin to the exact commit or the version.
  # uses: xcpep/aws-ecr-push-action@94c8e9be9b71c5cdb6e96cee4bcdc22251782d5c
      uses: xcpep/aws-ecr-push-action@v0.1
      with:
        repo: newrepo
        region: ap-south-1
    
   
          
      
